### ISSUE TITLE
Repo down

### ISSUE THREAD

**Issue by nicolasf** [blackstoneaudio/Kormatter#1]
The repo seems to be down.

Do you plan to publish this on mavenCentral?

**Comment by alexwhb** [comment]
Hey @nicolasf, no plans to put it on Maven Central. I just rebooted my server, however. Working on some stability fixes to my current infrastructure. Hopefully will be more consistant soon. Note your Maven config will need to look like this: ```maven("https://repos.awhb.dev/releases")```

I've tried putting my projects on Maven Central in the past. That service was incredibly confusing and old school, so I decided to just host my own maven repo. I really wish there was a more modern and easy to use hosted Maven system out there, but I couldn't find anything. Probably the worst aspect of the JVM ecosystem in my opinion.
